set(CTEST_PROJECT_NAME       "myCICE")
set(CTEST_DROP_METHOD        "http")
set(CTEST_DROP_SITE          "my.cdash.org")
set(CTEST_DROP_LOCATION      "/submit.php?project=myCICE")
set(CTEST_DROP_SITE_CDASH    TRUE)
set(CTEST_NIGHTLY_START_TIME "01:00:00 CET")
