
# Add your custom executables here in the form:
# add_test(<descriptive_name> <executable_name> [<arg1> <arg2> ...])
# 
# Make your test return 0 for success, nonzero for failure.

add_test(smoke_gx3_8x2_diag1_run5day_build grep "PASS.*smoke_gx3_8x2_diag1_run5day.*build" results.log)
add_test(smoke_gx3_8x2_diag1_run5day_run grep "PASS.*smoke_gx3_8x2_diag1_run5day.*run" results.log)
add_test(smoke_gx3_8x2_diag1_run5day_compare grep "PASS.*smoke_gx3_8x2_diag1_run5day.*compare" results.log)
add_test(smoke_gx3_8x2_diag24_run1year_medium_build grep "PASS.*smoke_gx3_8x2_diag24_run1year_medium.*build" results.log)
add_test(smoke_gx3_8x2_diag24_run1year_medium_run grep "PASS.*smoke_gx3_8x2_diag24_run1year_medium.*run" results.log)
add_test(smoke_gx3_8x2_diag24_run1year_medium_compare grep "PASS.*smoke_gx3_8x2_diag24_run1year_medium.*compare" results.log)
add_test(smoke_gx3_4x1_debug_diag1_run5day_build grep "PASS.*smoke_gx3_4x1_debug_diag1_run5day.*build" results.log)
add_test(smoke_gx3_4x1_debug_diag1_run5day_run grep "PASS.*smoke_gx3_4x1_debug_diag1_run5day.*run" results.log)
add_test(smoke_gx3_4x1_debug_diag1_run5day_compare grep "PASS.*smoke_gx3_4x1_debug_diag1_run5day.*compare" results.log)
add_test(smoke_gx3_8x2_debug_diag1_run5day_build grep "PASS.*smoke_gx3_8x2_debug_diag1_run5day.*build" results.log)
add_test(smoke_gx3_8x2_debug_diag1_run5day_run grep "PASS.*smoke_gx3_8x2_debug_diag1_run5day.*run" results.log)
add_test(smoke_gx3_8x2_debug_diag1_run5day_compare grep "PASS.*smoke_gx3_8x2_debug_diag1_run5day.*compare" results.log)
add_test(smoke_gx3_4x2_diag1_run5day_build grep "PASS.*smoke_gx3_4x2_diag1_run5day.*build" results.log)
add_test(smoke_gx3_4x2_diag1_run5day_run grep "PASS.*smoke_gx3_4x2_diag1_run5day.*run" results.log)
add_test(smoke_gx3_4x2_diag1_run5day_compare grep "PASS.*smoke_gx3_4x2_diag1_run5day.*compare" results.log)
add_test(smoke_gx3_4x2_diag1_run5day_bfbcomp grep "PASS.*smoke_gx3_4x2_diag1_run5day.*bfbcomp" results.log)
add_test(smoke_gx3_4x1_diag1_run5day_thread_build grep "PASS.*smoke_gx3_4x1_diag1_run5day_thread.*build" results.log)
add_test(smoke_gx3_4x1_diag1_run5day_thread_run grep "PASS.*smoke_gx3_4x1_diag1_run5day_thread.*run" results.log)
add_test(smoke_gx3_4x1_diag1_run5day_thread_compare grep "PASS.*smoke_gx3_4x1_diag1_run5day_thread.*compare" results.log)
add_test(smoke_gx3_4x1_diag1_run5day_build grep "PASS.*smoke_gx3_4x1_diag1_run5day.*build" results.log)
add_test(smoke_gx3_4x1_diag1_run5day_run grep "PASS.*smoke_gx3_4x1_diag1_run5day.*run" results.log)
add_test(smoke_gx3_4x1_diag1_run5day_compare grep "PASS.*smoke_gx3_4x1_diag1_run5day.*compare" results.log)
add_test(smoke_gx3_4x1_diag1_run5day_bfbcomp grep "PASS.*smoke_gx3_4x1_diag1_run5day.*bfbcomp" results.log)
add_test(restart_gx3_8x1_build grep "PASS.*restart_gx3_8x1.*build" results.log)
add_test(restart_gx3_8x1_run_initial grep "PASS.*restart_gx3_8x1.*run-initial" results.log)
add_test(restart_gx3_8x1_run_restart grep "PASS.*restart_gx3_8x1.*run-restart" results.log)
add_test(restart_gx3_8x1_exact_restart grep "PASS.*restart_gx3_8x1.*exact-restart" results.log)
add_test(restart_gx3_8x1_compare grep "PASS.*restart_gx3_8x1.*compare" results.log)
add_test(restart_gx3_4x2_debug_build grep "PASS.*restart_gx3_4x2_debug.*build" results.log)
add_test(restart_gx3_4x2_debug_run_initial grep "PASS.*restart_gx3_4x2_debug.*run-initial" results.log)
add_test(restart_gx3_4x2_debug_run_restart grep "PASS.*restart_gx3_4x2_debug.*run-restart" results.log)
add_test(restart_gx3_4x2_debug_exact_restart grep "PASS.*restart_gx3_4x2_debug.*exact-restart" results.log)
add_test(restart_gx3_4x2_debug_compare grep "PASS.*restart_gx3_4x2_debug.*compare" results.log)
