# Test         Grid    PEs        Sets    BFB-compare
smoke          gx3     8x2        diag1,run5day
smoke          gx3     1x1        debug,diag1,run2day
smoke          gx3     1x4        debug,diag1,run2day
smoke          gx3     4x1        debug,diag1,run5day
restart        gx3     8x2        debug
restart        gx3     8x2        debug,gx3nc
smoke          gx3     8x2        diag24,run1year,long
smoke          gx3     7x2        diag1,bigdiag,run1day,diagpt1
decomp         gx3     4x2x25x29x5  none
smoke          gx3     4x2        diag1,run5day             smoke_gx3_8x2_diag1_run5day
smoke          gx3     4x1        diag1,run5day,thread      smoke_gx3_8x2_diag1_run5day
smoke          gx3     1x8        diag1,run5day,evp1d
restart        gx1    40x4        droundrobin,medium
restart        tx1    40x4        dsectrobin,medium
restart        tx1    40x4        dsectrobin,medium,jra55do
restart        gx3     4x4        medium
restart        gx3     4x4        gx3nc,short
restart        gx3    10x4        maskhalo,medium
restart        gx3     6x2        alt01
restart        gx3     8x2        alt02
restart        gx3     4x2        alt03
restart        gx3    12x2        alt03,maskhalo,droundrobin
restart        gx3     4x4        alt04
restart        gx3     4x4        alt05,medium
restart        gx3     8x2        alt06
restart        gx3     8x2        pondsealvl
restart        gx3    16x2        snicar
restart        gx3    18x2        debug,maskhalo
restart        gx3     6x2        alt01,debug,short
restart        gx3     8x2        alt02,debug,short
restart        gx3     4x2        alt03,debug,short
smoke          gx3    12x2        alt03,debug,short,maskhalo,droundrobin
smoke          gx3     4x4        alt04,debug,short
smoke          gx3     4x4        alt05,debug,short
smoke          gx3     8x2        alt06,debug,short
smoke          gx3     8x3        alt07,debug,short
smoke          gx3     8x2        congel,debug,short
smoke          gx3    16x2        snicar,debug,short
smoke          gx3    12x2        snicartest,debug,short
smoke          gx3     10x2       debug,diag1,run5day,gx3sep2
smoke          gx3     7x2x5x29x12 diag1,bigdiag,run1day,debug
restart        gbox128 4x2        short
restart        gbox128 4x2        boxnodyn,short
restart        gbox128 4x2        boxnodyn,short,debug
restart        gbox128 2x2        boxadv,short
smoke          gbox128 2x2        boxadv,short,debug
restart        gbox128 4x4        boxrestore,medium
smoke          gbox128 4x4        boxrestore,short,debug
restart        gbox80  1x1        box2001
smoke          gbox80  1x1        boxslotcyl
smoke          gbox12  1x1x12x12x1  boxchan,diag1,debug
restart        gx3     8x2        modal
smoke          gx3     8x2        bgcz,diag1,run5day
smoke          gx3     8x2        jra55do
smoke          gx3     8x2        bgczm,diag1,debug
smoke          gx3    12x2        zaero,diag1,debug
#smoke          gx3     8x1        bgcskl,diag1,debug
#smoke          gx3     4x1       bgcz,thread        smoke_gx3_8x2_bgcz
#restart        gx1     4x2        bgcsklclim,medium
restart        gx1     8x1        bgczclim,medium
restart        gx3    16x1        zaero,icdefault,snwitdrdg,snwgrain
smoke          gx1    24x1        medium,run90day,yi2008
smoke          gx1    24x1        medium,run90day,yi2008,jra55do
smoke          gx3     8x1        medium,run90day,yi2008
restart        gx1    24x1        short
restart        gx1    16x2        seabedLKD,gx1apr,short,debug
restart        gx1    15x2        seabedprob
restart        gx1    32x1        gx1prod
smoke          gx3     4x2        fsd1,diag24,run5day,debug
smoke          gx3     8x2        fsd12,diag24,run5day
restart        gx3     4x2        fsd12,debug,short
smoke          gx3     8x2        fsd12ww3,diag24,run1day
smoke          gx3     4x1        isotope,debug
restart        gx3     8x2        isotope
smoke          gx3     4x1        snwitdrdg,snwgrain,icdefault,debug
smoke          gx3     4x1        snw30percent,icdefault,debug
restart        gx3     8x2        snwitdrdg,icdefault,snwgrain
restart        gx3     4x4        gx3ncarbulk,iobinary,medium
restart        gx3     4x4        cdf64,histall,precision8,medium
smoke          gx3    30x1        bgcz,histall
smoke          gx3    14x2        fsd12,histall
smoke          gx3     4x1        dynpicard
restart        gx3     8x2        gx3ncarbulk,debug
restart        gx3     4x4        diag1,gx3ncarbulk,short
smoke          gx3     4x1        calcdragio
restart        gx3     4x2        atmbndyconstant
restart        gx3     4x2        atmbndymixed
smoke          gx3    12x2        diag1,run5day,restaicetest,debug
