
#-----------------------------------------------------------
# Baseline generating run

if (${ICE_BASEGEN} != ${ICE_SPVAL}) then
  
  set baseline_dir = ${ICE_BASELINE}/${ICE_BASEGEN}/${ICE_TESTNAME}

  if (-e ${baseline_dir}) then
    echo "FAIL ${ICE_TESTNAME} generate baseline-already-exists" >> ${ICE_CASEDIR}/test_output
    echo "Baseline directory (${baseline_dir}) already exists. Exiting..."
  else
    mkdir -p ${baseline_dir}
    cp -p -r ${ICE_RUNDIR}/* ${baseline_dir}/
    echo "PASS ${ICE_TESTNAME} generate ${ICE_BASEGEN}" >> ${ICE_CASEDIR}/test_output
  endif
endif

#-----------------------------------------------------------
# Baseline comparing run

if (${ICE_BASECOM} != ${ICE_SPVAL}) then
  set test_dir = ${ICE_RUNDIR}/restart
  set base_dir  = ${ICE_BASELINE}/${ICE_BASECOM}/${ICE_TESTNAME}/restart

  set baseline_log = `ls -1t ${ICE_BASELINE}/${ICE_BASECOM}/${ICE_TESTNAME}/cice.runlog* | head -1`
  set btimeloop = -1
  set bdynamics = -1
  set bcolumn = -1
  if (${baseline_log} != "" ) then
    set btimeloop = `grep TimeLoop ${baseline_log} | grep Timer | cut -c 22-32`
    set bdynamics = `grep Dynamics ${baseline_log} | grep Timer | cut -c 22-32`
    set bcolumn   = `grep Column   ${baseline_log} | grep Timer | cut -c 22-32`
    if (${btimeloop} == "") set btimeloop = -1
    if (${bdynamics} == "") set bdynamics = -1
    if (${bcolumn}   == "") set bcolumn = -1
  endif

  echo ""
  echo "Regression Compare Mode:"
  echo "base_dir: ${base_dir}"
  echo "test_dir: ${test_dir}"

  ${ICE_CASEDIR}/casescripts/comparebfb.csh ${base_dir} ${test_dir}
  set bfbstatus = $?
  if ( ${bfbstatus} == 0 ) then
    echo "PASS ${ICE_TESTNAME} compare ${ICE_BASECOM} ${btimeloop} ${bdynamics} ${bcolumn}" >> ${ICE_CASEDIR}/test_output
    echo "Regression baseline and test dataset are identical"
  else if ( ${bfbstatus} == 2 ) then
    echo "MISS ${ICE_TESTNAME} compare ${ICE_BASECOM}  ${btimeloop} ${bdynamics} ${bcolumn} missing-data" >> ${ICE_CASEDIR}/test_output
    echo "Missing data"
  else
    echo "FAIL ${ICE_TESTNAME} compare ${ICE_BASECOM} ${btimeloop} ${bdynamics} ${bcolumn} different-data" >> ${ICE_CASEDIR}/test_output
    echo "Regression baseline and test dataset are different"
  endif
endif

#-----------------------------------------------------------

# BFB Compare runs

if (${ICE_BFBCOMP} != ${ICE_SPVAL}) then

  set test_dir = ${ICE_RUNDIR}/restart
  set base_dir = ${ICE_RUNDIR}/../${ICE_BFBCOMP}.${ICE_TESTID}/restart

  echo ""
  echo "bfb Compare Mode:"
  echo "base_dir: ${base_dir}"
  echo "test_dir: ${test_dir}"

  ${ICE_CASEDIR}/casescripts/comparebfb.csh ${base_dir} ${test_dir}
  set bfbstatus = $?
  if (${bfbstatus} == 0) then
    echo "PASS ${ICE_TESTNAME} bfbcomp ${ICE_BFBCOMP}" >> ${ICE_CASEDIR}/test_output
    echo "bfb baseline and test dataset are identical"
  else if (${bfbstatus} == 2) then
    echo "MISS ${ICE_TESTNAME} bfbcomp ${ICE_BFBCOMP} missing-data" >> ${ICE_CASEDIR}/test_output
    echo "Missing data"
  else
    echo "FAIL ${ICE_TESTNAME} bfbcomp ${ICE_BFBCOMP} different-data" >> ${ICE_CASEDIR}/test_output
    echo "bfbcomp and test dataset are different"
  endif
endif

#-----------------------------------------------------------
