
#----------------------------------------------------
# Run the CICE model
# cice.run returns -1 if run did not complete successfully

./cice.run
set rres="$status"

set log_file = `ls -t1 ${ICE_RUNDIR}/cice.runlog* | head -1`

grep ' TEST COMPLETED SUCCESSFULLY' ${log_file}
set tres="$status"

mv -f ${ICE_CASEDIR}/test_output ${ICE_CASEDIR}/test_output.prev
cat ${ICE_CASEDIR}/test_output.prev | grep -iv "${ICE_TESTNAME} run" >! ${ICE_CASEDIR}/test_output
mv -f ${ICE_CASEDIR}/test_output ${ICE_CASEDIR}/test_output.prev
cat ${ICE_CASEDIR}/test_output.prev | grep -iv "${ICE_TESTNAME} test" >! ${ICE_CASEDIR}/test_output
rm -f ${ICE_CASEDIR}/test_output.prev

set rgrade = PASS
if ( $rres != 0 ) then
  set rgrade = FAIL
endif
set tgrade = PASS
if ( $tres != 0 ) then
  set tgrade = FAIL
endif

echo "$rgrade ${ICE_TESTNAME} run " >> ${ICE_CASEDIR}/test_output
echo "$tgrade ${ICE_TESTNAME} test " >> ${ICE_CASEDIR}/test_output

if ( "$rgrade" == "FAIL" || "$tgrade" == "FAIL") then
  echo "ERROR: Test failed"
  exit 99
endif

