!|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

 module ice_gather_scatter

!  This module contains routines for gathering data to a single
!  processor from a distributed array, and scattering data from a
!  single processor to a distributed array.
!
!  NOTE: The arrays gathered and scattered are assumed to have
!        horizontal dimensions (nx_block, ny_block).
!
! author: Phil Jones, LANL
! Oct. 2004: Adapted from POP version by William H. Lipscomb, LANL
! Jan. 2008: Elizabeth Hunke replaced old routines with new POP
!              infrastructure, added specialized routine scatter_global_stress
! Jul, 2026: T. Craig significant cleanup

#ifndef NO_MPI
   use mpi   ! MPI Fortran module
#endif
   use ice_kinds_mod
   use ice_communicate, only: my_task
#ifndef NO_MPI
   use ice_communicate, only: mpiR8, mpiR4, mpitag_gs, MPI_COMM_ICE, &
       ice_barrier, add_mpi_barriers
#endif
   use ice_constants, only: spval_dbl, spval, spval_int, c0, c1, &
       field_loc_center, field_loc_NEcorner, field_loc_Nface, field_loc_Eface, &
       field_loc_noupdate, &
       field_type_scalar, field_type_vector, field_type_angle, &
       field_type_noupdate
   use ice_blocks, only: block, nx_block, ny_block, nblocks_tot, get_block, &
       nblocks_x, nblocks_y, nghost, i_global, j_global, &
       ew_boundary_type, ns_boundary_type
   use ice_distribution, only: distrb
   use ice_domain_size, only: nx_global, ny_global
   use ice_exit, only: abort_ice
   use icepack_intfc, only: icepack_warnings_flush, icepack_warnings_aborted

   implicit none
   private

   public :: gather_global,      &
             scatter_global

!-----------------------------------------------------------------------
!
!  overload module functions
!
!-----------------------------------------------------------------------

   interface gather_global
     module procedure gather_globalR8, &
                      gather_globalR4, &
                      gather_globalI4, &
                      gather_globalL1
   end interface

   interface scatter_global
     module procedure scatter_globalR8, &
                      scatter_globalR4, &
                      scatter_globalI4, &
                      scatter_globalL1
   end interface

!-----------------------------------------------------------------------
!
!  module variables
!
!-----------------------------------------------------------------------

!***********************************************************************

 contains

!***********************************************************************
! autogenerate start
!***********************************************************************

 subroutine gather_globalR8(ARRAY_G, ARRAY, dst_task, src_dist, fillValue, grid_ext)

!  Generated by ./generate_GatherScatter.sh on 2026-08-09
!  This subroutine gathers a distributed array to a global-sized
!  array on the processor dst_task.
!  If grid_ext is true, then ARRAY_G is extended grid
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global

   integer (int_kind), intent(in) :: &
      dst_task   ! task to which array should be gathered

   type (distrb), intent(in) :: &
      src_dist   ! distribution of blocks in the source array

   real (dbl_kind), dimension(:,:,:), intent(in) :: &
      ARRAY      ! array containing horizontal slab of distributed field

   real (dbl_kind), intent(in), optional :: &
      fillValue  ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext   ! extended global grid flag

   real (dbl_kind), dimension(:,:), intent(inout) :: &
      ARRAY_G    ! array containing global horizontal field on dst_task

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind) :: &
      i,j,n,          &! dummy loop counters
      iblock,jblock,  &! block index
      ilo,ihi,jlo,jhi  ! block sizes

#ifndef NO_MPI
   integer (int_kind) :: &
      nsends,         &! number of actual sends
      src_block,      &! block locator for send
      ierr             ! MPI error flag

   integer (int_kind), dimension(MPI_STATUS_SIZE) :: &
      status

   integer (int_kind), dimension(:), allocatable :: &
      snd_request

   integer (int_kind), dimension(:,:), allocatable :: &
      snd_status

   real (dbl_kind), dimension(:,:), allocatable :: &
      msg_buffer
#endif

   real (dbl_kind) :: &
      lfillValue  ! local special value

   logical (log_kind) :: &
      lext        ! local grid_ext global grid flag

   type (block) :: &
      this_block  ! block info for current block

   real (dbl_kind), dimension(:,:), allocatable :: &
      LARRAY_G    ! array containing global horizontal field on dst_task
                  ! but with indexing that matches nx_global, ny_global
                  ! to simplify overlapping ext and non-ext coding.
                  ! for non-ext, ARRAY_G and LARRAY_G are (nx_global,ny_global).
                  ! for ext incoming ARRAY_G is (1:nx_global+2*nghost,1:ny_global+2*nghost)
                  ! LARRAY_G is same size, but indexing is
                  !            (1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
                  ! Could maybe use a pointer but a separate array and copy is more robust

   character(len=*), parameter :: subname = '(gather_globalR8)'

   if (present(fillValue)) then
      lfillValue = fillValue
   else
      lfillValue = spval_dbl
   endif

   if (present(grid_ext)) then
      lext = grid_ext
   else
      lext = .false.
   endif

!-----------------------------------------------------------------------
!
!  if this task is the dst_task, copy local blocks into the global
!  array and post receives for non-local blocks.
!
!-----------------------------------------------------------------------

   if (my_task == dst_task) then

      if (lext) then
         allocate(LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost))
         LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost) = ARRAY_G(1:nx_global+2,1:ny_global+2)
      else
         allocate(LARRAY_G(1:nx_global,1:ny_global))
         LARRAY_G(:,:) = ARRAY_G(:,:)
      endif

      do n=1,nblocks_tot

         this_block = get_block(n,n)
         ilo = this_block%ilo
         ihi = this_block%ihi
         jlo = this_block%jlo
         jhi = this_block%jhi
         iblock = this_block%iblock
         jblock = this_block%jblock

         !*** copy local blocks

         if (src_dist%blockLocation(n) == my_task+1) then

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = ARRAY(i,j,src_dist%blockLocalID(n))
            end do
            end do

            !*** fill outside halo for extended grid gather

            if (lext) then
               ! south
               if (jblock == 1) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),j-nghost) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! north
               if (jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),ny_global+j) = ARRAY(i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! west
               if (iblock == 1) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(i-nghost,this_block%j_glob(j)) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! east
               if (iblock == nblocks_x) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(nx_global+i,this_block%j_glob(j)) = ARRAY(ihi+i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! southwest
               if (iblock == 1 .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,j-nghost) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! northwest
               if (iblock == 1 .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,ny_global+j) = ARRAY(i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! southeast
               if (iblock == nblocks_x .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,j-nghost) = ARRAY(ihi+i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! northeast
               if (iblock == nblocks_x .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,ny_global+nghost) = ARRAY(ihi+i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif
            endif

         !*** fill land blocks with special values

         else if (src_dist%blockLocation(n) == 0) then

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = lfillValue
            end do
            end do

         endif

      end do

#ifndef NO_MPI
      !*** copy blocks from other tasks

      allocate (msg_buffer(nx_block,ny_block))

      do n=1,nblocks_tot
         if (src_dist%blockLocation(n) > 0 .and. &
             src_dist%blockLocation(n) /= my_task+1) then

            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi
            iblock = this_block%iblock
            jblock = this_block%jblock

            call MPI_RECV(msg_buffer, size(msg_buffer), &
                 mpiR8, src_dist%blockLocation(n)-1, 3*mpitag_gs+n, &
                 MPI_COMM_ICE, status, ierr)

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = msg_buffer(i,j)
            end do
            end do

            !*** fill outside halo for extended grid gather

            if (lext) then
               ! south
               if (jblock == 1) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),j-nghost) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! north
               if (jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),ny_global+j) = msg_buffer(i,jhi+j)
                  enddo
                  enddo
               endif

               ! west
               if (iblock == 1) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(i-nghost,this_block%j_glob(j)) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! east
               if (iblock == nblocks_x) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(nx_global+i,this_block%j_glob(j)) = msg_buffer(ihi+i,j)
                  enddo
                  enddo
               endif

               ! southwest
               if (iblock == 1 .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,j-nghost) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! northwest
               if (iblock == 1 .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,ny_global+j) = msg_buffer(i,jhi+j)
                  enddo
                  enddo
               endif

               ! southeast
               if (iblock == nblocks_x .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,j-nghost) = msg_buffer(ihi+i,j)
                  enddo
                  enddo
               endif

               ! northeast
               if (iblock == nblocks_x .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,ny_global+nghost) = msg_buffer(ihi+i,jhi+j)
                  enddo
                  enddo
               endif
            endif ! lext
         endif
      end do

      deallocate(msg_buffer)
#endif

      ! copy LARRAY_G to ARRAY_G, offset extended grid index

      if (lext) then
         ARRAY_G(1:nx_global+2,1:ny_global+2) = LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
      else
         ARRAY_G(1:nx_global,1:ny_global) = LARRAY_G(1:nx_global,1:ny_global)
      endif
      deallocate(LARRAY_G)

#ifndef NO_MPI
!-----------------------------------------------------------------------
!
!  otherwise send data to dst_task
!
!-----------------------------------------------------------------------

   else

      allocate(snd_request(nblocks_tot), &
               snd_status (MPI_STATUS_SIZE, nblocks_tot))

      nsends = 0
      do n=1,nblocks_tot
         if (src_dist%blockLocation(n) == my_task+1) then
            nsends = nsends + 1
            src_block = src_dist%blockLocalID(n)
            call MPI_ISEND(ARRAY(1,1,src_block), nx_block*ny_block, &
                 mpiR8, dst_task, 3*mpitag_gs+n, &
                 MPI_COMM_ICE, snd_request(nsends), ierr)
         endif
      end do

      if (nsends > 0) call MPI_WAITALL(nsends, snd_request, snd_status, ierr)
      deallocate(snd_request, snd_status)
#endif

   endif

#ifndef NO_MPI
   if (add_mpi_barriers) then
      call ice_barrier()
   endif
#endif

!-----------------------------------------------------------------------

 end subroutine gather_globalR8

!***********************************************************************

 subroutine scatter_globalR8(ARRAY, ARRAY_G, src_task, dst_dist, &
                             field_loc, field_type, fillValue, &
                             grid_ext)

!  Generated by ./generate_GatherScatter.sh on 2026-08-09
!  This subroutine scatters a global sized array from src_task to all
!  processors.
!  If grid_ext is true, then ARRAY_G is extended grid and updates outer halo
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global and outer
!    halo is updated for cyclic and tripole bcs.
!  If grid_ext is false and interior is true, then only the interior data will 
!    be scattered, no outer halo bcs will be applied

   integer (int_kind), intent(in) :: &
      src_task        ! task from which array should be scattered

   type (distrb), intent(in) :: &
      dst_dist        ! distribution of resulting blocks

   real (dbl_kind), dimension(:,:), intent(in) :: &
      ARRAY_G         ! array containing global field on src_task

   integer (int_kind), intent(in), optional :: &
      field_type,    &! id for type of field (scalar, vector, angle)
      field_loc       ! id for location on horizontal grid
                      !  (center, NEcorner, Nface, Eface)

   real (dbl_kind), intent(in), optional :: &
      fillValue       ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext        ! extended grid flag

   real (dbl_kind), dimension(:,:,:), intent(inout) :: &
      ARRAY           ! array containing distributed field

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind) :: &
      i,j,n,         &! dummy loop indices
      ilo,ihi,jlo,jhi,&! block indices
      isrc, jsrc,    &! source addresses
      ioffset, joffset,   &! offsets for tripole boundary conditions
      isign,         &! sign factor for tripole boundary conditions
      dst_block       ! location of block in dst array

   real (dbl_kind) :: &
      efac            ! linear extrapolation factor

   type (block) :: &
      this_block      ! block info for current block

   real (dbl_kind) :: &
      lfillValue      ! local special value

   logical (log_kind) :: &
      lext,          &! local extended global grid flag
      noupdate        ! flag if noupdate is on

   real (dbl_kind), dimension(:,:), allocatable :: &
      LARRAY_G    ! array containing global horizontal field on dst_task
                  ! but with indexing that matches nx_global, ny_global
                  ! to simplify overlapping ext and non-ext coding.
                  ! for non-ext, ARRAY_G and LARRAY_G are (nx_global,ny_global).
                  ! for ext incoming ARRAY_G is (1:nx_global+2*nghost,1:ny_global+2*nghost)
                  ! LARRAY_G is same size, but indexing is
                  !            (1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
                  ! Could maybe use a pointer but a separate array and copy is more robust

#ifndef NO_MPI
   integer (int_kind) :: &
      nrecvs,        &! actual number of messages received
      ierr            ! MPI error flag

   integer (int_kind), dimension(:), allocatable :: &
      rcv_request     ! request array for receives

   integer (int_kind), dimension(:,:), allocatable :: &
      rcv_status      ! status array for receives

   real (dbl_kind), dimension(:,:), allocatable :: &
      msg_buffer      ! buffer for sending blocks
#endif

   character(len=*), parameter :: subname = '(scatter_globalR8)'

   if (present(fillValue)) then
      lfillValue = fillValue
   else
      lfillValue = c0
   endif

   if (present(grid_ext)) then
      lext = grid_ext
   else
      lext = .false.
   endif

   noupdate = .false.
   if (present(field_loc)) then
      if (field_loc == field_loc_noupdate) then
         noupdate = .true.
      endif
   endif
   if (present(field_type)) then
      if (field_type == field_type_noupdate) then
         noupdate = .true.
      endif
   endif

   ! check size of global grid
   if (my_task == src_task) then
      if (lext) then
         if (size(ARRAY_G,dim=1)/= nx_global+2*nghost .or. size(ARRAY_G,dim=2) /= ny_global+2*nghost) then
            call abort_ice(subname//'ERROR: grid_ext = true, wrong ARRAY_G size')
         endif
      else
         if (size(ARRAY_G,dim=1)/= nx_global .or. size(ARRAY_G,dim=2) /= ny_global) then
            call abort_ice(subname//'ERROR: grid_ext = false, wrong ARRAY_G size')
         endif
      endif
   endif

   ARRAY = lfillValue

   isign = -99
   ioffset = -999
   joffset = -999
   if (.not.lext .and. .not.noupdate .and. &
      (ns_boundary_type == 'tripole' .or. ns_boundary_type == 'tripoleT')) then

      select case (field_type)
      case (field_type_scalar)
         isign =  1
      case (field_type_vector)
         isign = -1
      case (field_type_angle)
         isign = -1
      case (field_type_noupdate) ! ghost cells never used - use cell center
         isign =  1
      case default
         call abort_ice(subname//'ERROR: Unknown field kind')
      end select

      if (ns_boundary_type == 'tripole') then
         ioffset = 0
         joffset = 0
      else ! tripoleT fold
         ioffset = -1
         joffset = 1
      endif

      select case (field_loc)
        case (field_loc_center)     ! cell center location
           !ioffset = ioffset
           !joffset = joffset
        case (field_loc_NEcorner)   ! cell corner (velocity) location
           ioffset = ioffset + 1
           joffset = joffset + 1
        case (field_loc_Eface)      ! cell east face
           ioffset = ioffset + 1
           !joffset = joffset
        case (field_loc_Nface)      ! cell north face
           !ioffset = ioffset
           joffset = joffset + 1
        case (field_loc_noupdate)   ! no update
           !ioffset = ioffset
           !joffset = joffset
        case default
           call abort_ice(subname//'ERROR: Unknown field location')
      end select

   endif ! not lext

!-----------------------------------------------------------------------
!
!  if this task is the src_task, compute updated LARRAY_G which contains
!  outer halo extended grid from ARRAY_G (extended or not), fill outer
!  halo in global array then scatter
!
!  i_global, j_global are indexed 1-nghost:n*_global+nghost
!
!-----------------------------------------------------------------------

   if (my_task == src_task) then

      allocate(LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost))

      LARRAY_G = lfillValue
      if (lext) then
         do j = 1-nghost, ny_global+nghost
         do i = 1-nghost, nx_global+nghost
            LARRAY_G(i,j) = ARRAY_G(i+nghost,j+nghost)
         enddo
         enddo
      else

         ! fill cells that can be directly copied

         do j = 1-nghost, ny_global+nghost
         do i = 1-nghost, nx_global+nghost
            isrc = i_global(i)
            jsrc = j_global(j)
            if (isrc >= 1 .and. isrc <= nx_global .and. &
                jsrc >= 1 .and. jsrc <= ny_global) then
               ! copy valid cell directly
               LARRAY_G(i,j) = ARRAY_G(isrc,jsrc)
            endif
         enddo
         enddo

         ! fill outer halo, only if noupdate is false
         ! do north/south boundary first (partly due to tripole feature) (1:nx_global)
         ! then do east/west including corners (1-nghost:ny_global+nghost)

         if (.not.noupdate) then
            if (ns_boundary_type == 'tripole' .or. ns_boundary_type == 'tripoleT') then
               do j = ny_global, ny_global+nghost
               ! north of active cells
               do i = 1, nx_global
                  isrc = nx_global - i + 1 - ioffset   ! ioffset = 0 for u center, ioffset = 1 for T center
                  jsrc = ny_global - (j-ny_global) - joffset + 1  ! joffset = 0 for u center, joffset = 1 for T center
                  if (isrc < 1        ) isrc = isrc + nx_global
                  if (isrc > nx_global) isrc = isrc - nx_global

                  !*** for center and Eface on u-fold, and NE corner and Nface
                  !*** on T-fold, do not need to replace
                  !*** top row of physical domain, so jsrc should be greater than j

                  if (jsrc > j) then
                     ! do nothing
                  elseif (jsrc == j) then
                     ! don't average in the scatter even though halo update does
                     ! LARRAY_G(i,j) = 0.5_dbl_kind * (ARRAY_G(i,jsrc) + isign*ARRAY_G(isrc,jsrc))
                  else
                     ! copy
                     LARRAY_G(i,j) = isign * ARRAY_G(isrc,jsrc)
                  endif
               enddo
               enddo
            else
               !--- bottom edge
               do j = 1-nghost, 0
               do i = 1, nx_global
                  if (ns_boundary_type == 'cyclic') then
                     LARRAY_G(i,j) = ARRAY_G(i,j+ny_global)
                  elseif (ns_boundary_type == 'zero_gradient') then
                     LARRAY_G(i,j) = ARRAY_G(i,1)
                  elseif (ns_boundary_type == 'linear_extrap') then
                     efac = real(2-j,dbl_kind)
                     LARRAY_G(i,j) = efac*ARRAY_G(i,1) - (efac-c1)*ARRAY_G(i,2)
                  endif
               enddo
               enddo
               !--- top edge
               do j = ny_global+1, ny_global+nghost
               do i = 1, nx_global
                  if (ns_boundary_type == 'cyclic') then
                     LARRAY_G(i,j) = ARRAY_G(i,j-ny_global)
                  elseif (ns_boundary_type == 'zero_gradient') then
                     LARRAY_G(i,j) = ARRAY_G(i,ny_global)
                  elseif (ns_boundary_type == 'linear_extrap') then
                     efac = real(j-ny_global+1,dbl_kind)
                     LARRAY_G(i,j) = efac*ARRAY_G(i,ny_global) - (efac-c1)*ARRAY_G(i,ny_global-1)
                  endif
               enddo
               enddo
            endif

            do j = 1-nghost, ny_global+nghost
            !--- left edge
            do i = 1-nghost, 0
               if (ew_boundary_type == 'cyclic') then
                  LARRAY_G(i,j) = LARRAY_G(i+nx_global,j)
               elseif (ew_boundary_type == 'zero_gradient') then
                  LARRAY_G(i,j) = LARRAY_G(1,j)
               elseif (ew_boundary_type == 'linear_extrap') then
                  efac = real(2-i,dbl_kind)
                  LARRAY_G(i,j) = efac*LARRAY_G(1,j) - (efac-c1)*LARRAY_G(2,j)
               endif
            enddo
            !--- right edge
            do i = nx_global+1, nx_global+nghost
               if (ew_boundary_type == 'cyclic') then
                  LARRAY_G(i,j) = LARRAY_G(i-nx_global,j)
               elseif (ew_boundary_type == 'zero_gradient') then
                  LARRAY_G(i,j) = LARRAY_G(nx_global,j)
               elseif (ew_boundary_type == 'linear_extrap') then
                  efac = real(i-nx_global+1,dbl_kind)
                  LARRAY_G(i,j) = efac*LARRAY_G(nx_global,j) - (efac-c1)*LARRAY_G(nx_global-1,j)
               endif
            enddo
            enddo

         endif   ! noupdate
      endif   ! lext

      !*** send non-local blocks away

#ifndef NO_MPI
      allocate (msg_buffer(nx_block,ny_block))

      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) > 0 .and. &
             dst_dist%blockLocation(n)-1 /= my_task) then

            msg_buffer = lfillValue
            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi

            do j=jlo-nghost,jhi+nghost
            do i=ilo-nghost,ihi+nghost
               ! fill entire block
               isrc = this_block%i_glob(ilo) + i - ilo
               jsrc = this_block%j_glob(jlo) + j - jlo
               msg_buffer(i,j) = LARRAY_G(isrc,jsrc)
            enddo
            enddo

            call MPI_SEND(msg_buffer, nx_block*ny_block, &
                          mpiR8, dst_dist%blockLocation(n)-1, 3*mpitag_gs+n, &
                          MPI_COMM_ICE, ierr)

         endif
      end do

      deallocate(msg_buffer)
#endif
      !*** copy any local blocks

      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) == my_task+1) then
            dst_block = dst_dist%blockLocalID(n)
            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi

            do j=jlo-nghost,jhi+nghost
            do i=ilo-nghost,ihi+nghost
               ! fill entire block
               isrc = this_block%i_glob(ilo) + i - ilo
               jsrc = this_block%j_glob(jlo) + j - jlo
               ARRAY(i,j,dst_block) = LARRAY_G(isrc,jsrc)
            enddo
            enddo
         endif
      end do

#ifndef NO_MPI
!-----------------------------------------------------------------------
!
!  otherwise receive data from src_task
!
!-----------------------------------------------------------------------

   else   ! my_task /= src_task

      allocate (rcv_request(nblocks_tot), &
                rcv_status(MPI_STATUS_SIZE, nblocks_tot))

      rcv_request = 0
      rcv_status  = 0

      nrecvs = 0
      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) == my_task+1) then
            nrecvs = nrecvs + 1
            dst_block = dst_dist%blockLocalID(n)
            call MPI_IRECV(ARRAY(1,1,dst_block), nx_block*ny_block, &
                          mpiR8, src_task, 3*mpitag_gs+n, &
                          MPI_COMM_ICE, rcv_request(nrecvs), ierr)
         endif
      end do

      if (nrecvs > 0) &
         call MPI_WAITALL(nrecvs, rcv_request, rcv_status, ierr)

      deallocate(rcv_request, rcv_status)
#endif
   endif   ! my_task == src_task

#ifndef NO_MPI
   if (add_mpi_barriers) then
     call ice_barrier()
   endif
#endif

!-----------------------------------------------------------------------

 end subroutine scatter_globalR8

!***********************************************************************

 subroutine gather_globalR4(ARRAY_G, ARRAY, dst_task, src_dist, fillValue, grid_ext)

!  Generated by ./generate_GatherScatter.sh on 2026-08-09
!  This subroutine gathers a distributed array to a global-sized
!  array on the processor dst_task.
!  If grid_ext is true, then ARRAY_G is extended grid
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global

   integer (int_kind), intent(in) :: &
      dst_task   ! task to which array should be gathered

   type (distrb), intent(in) :: &
      src_dist   ! distribution of blocks in the source array

   real (real_kind), dimension(:,:,:), intent(in) :: &
      ARRAY      ! array containing horizontal slab of distributed field

   real (real_kind), intent(in), optional :: &
      fillValue  ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext   ! extended global grid flag

   real (real_kind), dimension(:,:), intent(inout) :: &
      ARRAY_G    ! array containing global horizontal field on dst_task

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind) :: &
      i,j,n,          &! dummy loop counters
      iblock,jblock,  &! block index
      ilo,ihi,jlo,jhi  ! block sizes

#ifndef NO_MPI
   integer (int_kind) :: &
      nsends,         &! number of actual sends
      src_block,      &! block locator for send
      ierr             ! MPI error flag

   integer (int_kind), dimension(MPI_STATUS_SIZE) :: &
      status

   integer (int_kind), dimension(:), allocatable :: &
      snd_request

   integer (int_kind), dimension(:,:), allocatable :: &
      snd_status

   real (real_kind), dimension(:,:), allocatable :: &
      msg_buffer
#endif

   real (real_kind) :: &
      lfillValue  ! local special value

   logical (log_kind) :: &
      lext        ! local grid_ext global grid flag

   type (block) :: &
      this_block  ! block info for current block

   real (real_kind), dimension(:,:), allocatable :: &
      LARRAY_G    ! array containing global horizontal field on dst_task
                  ! but with indexing that matches nx_global, ny_global
                  ! to simplify overlapping ext and non-ext coding.
                  ! for non-ext, ARRAY_G and LARRAY_G are (nx_global,ny_global).
                  ! for ext incoming ARRAY_G is (1:nx_global+2*nghost,1:ny_global+2*nghost)
                  ! LARRAY_G is same size, but indexing is
                  !            (1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
                  ! Could maybe use a pointer but a separate array and copy is more robust

   character(len=*), parameter :: subname = '(gather_globalR4)'

   if (present(fillValue)) then
      lfillValue = fillValue
   else
      lfillValue = spval
   endif

   if (present(grid_ext)) then
      lext = grid_ext
   else
      lext = .false.
   endif

!-----------------------------------------------------------------------
!
!  if this task is the dst_task, copy local blocks into the global
!  array and post receives for non-local blocks.
!
!-----------------------------------------------------------------------

   if (my_task == dst_task) then

      if (lext) then
         allocate(LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost))
         LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost) = ARRAY_G(1:nx_global+2,1:ny_global+2)
      else
         allocate(LARRAY_G(1:nx_global,1:ny_global))
         LARRAY_G(:,:) = ARRAY_G(:,:)
      endif

      do n=1,nblocks_tot

         this_block = get_block(n,n)
         ilo = this_block%ilo
         ihi = this_block%ihi
         jlo = this_block%jlo
         jhi = this_block%jhi
         iblock = this_block%iblock
         jblock = this_block%jblock

         !*** copy local blocks

         if (src_dist%blockLocation(n) == my_task+1) then

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = ARRAY(i,j,src_dist%blockLocalID(n))
            end do
            end do

            !*** fill outside halo for extended grid gather

            if (lext) then
               ! south
               if (jblock == 1) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),j-nghost) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! north
               if (jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),ny_global+j) = ARRAY(i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! west
               if (iblock == 1) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(i-nghost,this_block%j_glob(j)) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! east
               if (iblock == nblocks_x) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(nx_global+i,this_block%j_glob(j)) = ARRAY(ihi+i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! southwest
               if (iblock == 1 .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,j-nghost) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! northwest
               if (iblock == 1 .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,ny_global+j) = ARRAY(i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! southeast
               if (iblock == nblocks_x .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,j-nghost) = ARRAY(ihi+i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! northeast
               if (iblock == nblocks_x .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,ny_global+nghost) = ARRAY(ihi+i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif
            endif

         !*** fill land blocks with special values

         else if (src_dist%blockLocation(n) == 0) then

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = lfillValue
            end do
            end do

         endif

      end do

#ifndef NO_MPI
      !*** copy blocks from other tasks

      allocate (msg_buffer(nx_block,ny_block))

      do n=1,nblocks_tot
         if (src_dist%blockLocation(n) > 0 .and. &
             src_dist%blockLocation(n) /= my_task+1) then

            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi
            iblock = this_block%iblock
            jblock = this_block%jblock

            call MPI_RECV(msg_buffer, size(msg_buffer), &
                 mpiR4, src_dist%blockLocation(n)-1, 3*mpitag_gs+n, &
                 MPI_COMM_ICE, status, ierr)

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = msg_buffer(i,j)
            end do
            end do

            !*** fill outside halo for extended grid gather

            if (lext) then
               ! south
               if (jblock == 1) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),j-nghost) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! north
               if (jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),ny_global+j) = msg_buffer(i,jhi+j)
                  enddo
                  enddo
               endif

               ! west
               if (iblock == 1) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(i-nghost,this_block%j_glob(j)) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! east
               if (iblock == nblocks_x) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(nx_global+i,this_block%j_glob(j)) = msg_buffer(ihi+i,j)
                  enddo
                  enddo
               endif

               ! southwest
               if (iblock == 1 .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,j-nghost) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! northwest
               if (iblock == 1 .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,ny_global+j) = msg_buffer(i,jhi+j)
                  enddo
                  enddo
               endif

               ! southeast
               if (iblock == nblocks_x .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,j-nghost) = msg_buffer(ihi+i,j)
                  enddo
                  enddo
               endif

               ! northeast
               if (iblock == nblocks_x .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,ny_global+nghost) = msg_buffer(ihi+i,jhi+j)
                  enddo
                  enddo
               endif
            endif ! lext
         endif
      end do

      deallocate(msg_buffer)
#endif

      ! copy LARRAY_G to ARRAY_G, offset extended grid index

      if (lext) then
         ARRAY_G(1:nx_global+2,1:ny_global+2) = LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
      else
         ARRAY_G(1:nx_global,1:ny_global) = LARRAY_G(1:nx_global,1:ny_global)
      endif
      deallocate(LARRAY_G)

#ifndef NO_MPI
!-----------------------------------------------------------------------
!
!  otherwise send data to dst_task
!
!-----------------------------------------------------------------------

   else

      allocate(snd_request(nblocks_tot), &
               snd_status (MPI_STATUS_SIZE, nblocks_tot))

      nsends = 0
      do n=1,nblocks_tot
         if (src_dist%blockLocation(n) == my_task+1) then
            nsends = nsends + 1
            src_block = src_dist%blockLocalID(n)
            call MPI_ISEND(ARRAY(1,1,src_block), nx_block*ny_block, &
                 mpiR4, dst_task, 3*mpitag_gs+n, &
                 MPI_COMM_ICE, snd_request(nsends), ierr)
         endif
      end do

      if (nsends > 0) call MPI_WAITALL(nsends, snd_request, snd_status, ierr)
      deallocate(snd_request, snd_status)
#endif

   endif

#ifndef NO_MPI
   if (add_mpi_barriers) then
      call ice_barrier()
   endif
#endif

!-----------------------------------------------------------------------

 end subroutine gather_globalR4

!***********************************************************************

 subroutine scatter_globalR4(ARRAY, ARRAY_G, src_task, dst_dist, &
                             field_loc, field_type, fillValue, &
                             grid_ext)

!  Generated by ./generate_GatherScatter.sh on 2026-08-09
!  This subroutine scatters a global sized array from src_task to all
!  processors.
!  If grid_ext is true, then ARRAY_G is extended grid and updates outer halo
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global and outer
!    halo is updated for cyclic and tripole bcs.
!  If grid_ext is false and interior is true, then only the interior data will 
!    be scattered, no outer halo bcs will be applied

   integer (int_kind), intent(in) :: &
      src_task        ! task from which array should be scattered

   type (distrb), intent(in) :: &
      dst_dist        ! distribution of resulting blocks

   real (real_kind), dimension(:,:), intent(in) :: &
      ARRAY_G         ! array containing global field on src_task

   integer (int_kind), intent(in), optional :: &
      field_type,    &! id for type of field (scalar, vector, angle)
      field_loc       ! id for location on horizontal grid
                      !  (center, NEcorner, Nface, Eface)

   real (real_kind), intent(in), optional :: &
      fillValue       ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext        ! extended grid flag

   real (real_kind), dimension(:,:,:), intent(inout) :: &
      ARRAY           ! array containing distributed field

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind) :: &
      i,j,n,         &! dummy loop indices
      ilo,ihi,jlo,jhi,&! block indices
      isrc, jsrc,    &! source addresses
      ioffset, joffset,   &! offsets for tripole boundary conditions
      isign,         &! sign factor for tripole boundary conditions
      dst_block       ! location of block in dst array

   real (dbl_kind) :: &
      efac            ! linear extrapolation factor

   type (block) :: &
      this_block      ! block info for current block

   real (real_kind) :: &
      lfillValue      ! local special value

   logical (log_kind) :: &
      lext,          &! local extended global grid flag
      noupdate        ! flag if noupdate is on

   real (real_kind), dimension(:,:), allocatable :: &
      LARRAY_G    ! array containing global horizontal field on dst_task
                  ! but with indexing that matches nx_global, ny_global
                  ! to simplify overlapping ext and non-ext coding.
                  ! for non-ext, ARRAY_G and LARRAY_G are (nx_global,ny_global).
                  ! for ext incoming ARRAY_G is (1:nx_global+2*nghost,1:ny_global+2*nghost)
                  ! LARRAY_G is same size, but indexing is
                  !            (1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
                  ! Could maybe use a pointer but a separate array and copy is more robust

#ifndef NO_MPI
   integer (int_kind) :: &
      nrecvs,        &! actual number of messages received
      ierr            ! MPI error flag

   integer (int_kind), dimension(:), allocatable :: &
      rcv_request     ! request array for receives

   integer (int_kind), dimension(:,:), allocatable :: &
      rcv_status      ! status array for receives

   real (real_kind), dimension(:,:), allocatable :: &
      msg_buffer      ! buffer for sending blocks
#endif

   character(len=*), parameter :: subname = '(scatter_globalR4)'

   if (present(fillValue)) then
      lfillValue = fillValue
   else
      lfillValue = 0._real_kind
   endif

   if (present(grid_ext)) then
      lext = grid_ext
   else
      lext = .false.
   endif

   noupdate = .false.
   if (present(field_loc)) then
      if (field_loc == field_loc_noupdate) then
         noupdate = .true.
      endif
   endif
   if (present(field_type)) then
      if (field_type == field_type_noupdate) then
         noupdate = .true.
      endif
   endif

   ! check size of global grid
   if (my_task == src_task) then
      if (lext) then
         if (size(ARRAY_G,dim=1)/= nx_global+2*nghost .or. size(ARRAY_G,dim=2) /= ny_global+2*nghost) then
            call abort_ice(subname//'ERROR: grid_ext = true, wrong ARRAY_G size')
         endif
      else
         if (size(ARRAY_G,dim=1)/= nx_global .or. size(ARRAY_G,dim=2) /= ny_global) then
            call abort_ice(subname//'ERROR: grid_ext = false, wrong ARRAY_G size')
         endif
      endif
   endif

   ARRAY = lfillValue

   isign = -99
   ioffset = -999
   joffset = -999
   if (.not.lext .and. .not.noupdate .and. &
      (ns_boundary_type == 'tripole' .or. ns_boundary_type == 'tripoleT')) then

      select case (field_type)
      case (field_type_scalar)
         isign =  1
      case (field_type_vector)
         isign = -1
      case (field_type_angle)
         isign = -1
      case (field_type_noupdate) ! ghost cells never used - use cell center
         isign =  1
      case default
         call abort_ice(subname//'ERROR: Unknown field kind')
      end select

      if (ns_boundary_type == 'tripole') then
         ioffset = 0
         joffset = 0
      else ! tripoleT fold
         ioffset = -1
         joffset = 1
      endif

      select case (field_loc)
        case (field_loc_center)     ! cell center location
           !ioffset = ioffset
           !joffset = joffset
        case (field_loc_NEcorner)   ! cell corner (velocity) location
           ioffset = ioffset + 1
           joffset = joffset + 1
        case (field_loc_Eface)      ! cell east face
           ioffset = ioffset + 1
           !joffset = joffset
        case (field_loc_Nface)      ! cell north face
           !ioffset = ioffset
           joffset = joffset + 1
        case (field_loc_noupdate)   ! no update
           !ioffset = ioffset
           !joffset = joffset
        case default
           call abort_ice(subname//'ERROR: Unknown field location')
      end select

   endif ! not lext

!-----------------------------------------------------------------------
!
!  if this task is the src_task, compute updated LARRAY_G which contains
!  outer halo extended grid from ARRAY_G (extended or not), fill outer
!  halo in global array then scatter
!
!  i_global, j_global are indexed 1-nghost:n*_global+nghost
!
!-----------------------------------------------------------------------

   if (my_task == src_task) then

      allocate(LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost))

      LARRAY_G = lfillValue
      if (lext) then
         do j = 1-nghost, ny_global+nghost
         do i = 1-nghost, nx_global+nghost
            LARRAY_G(i,j) = ARRAY_G(i+nghost,j+nghost)
         enddo
         enddo
      else

         ! fill cells that can be directly copied

         do j = 1-nghost, ny_global+nghost
         do i = 1-nghost, nx_global+nghost
            isrc = i_global(i)
            jsrc = j_global(j)
            if (isrc >= 1 .and. isrc <= nx_global .and. &
                jsrc >= 1 .and. jsrc <= ny_global) then
               ! copy valid cell directly
               LARRAY_G(i,j) = ARRAY_G(isrc,jsrc)
            endif
         enddo
         enddo

         ! fill outer halo, only if noupdate is false
         ! do north/south boundary first (partly due to tripole feature) (1:nx_global)
         ! then do east/west including corners (1-nghost:ny_global+nghost)

         if (.not.noupdate) then
            if (ns_boundary_type == 'tripole' .or. ns_boundary_type == 'tripoleT') then
               do j = ny_global, ny_global+nghost
               ! north of active cells
               do i = 1, nx_global
                  isrc = nx_global - i + 1 - ioffset   ! ioffset = 0 for u center, ioffset = 1 for T center
                  jsrc = ny_global - (j-ny_global) - joffset + 1  ! joffset = 0 for u center, joffset = 1 for T center
                  if (isrc < 1        ) isrc = isrc + nx_global
                  if (isrc > nx_global) isrc = isrc - nx_global

                  !*** for center and Eface on u-fold, and NE corner and Nface
                  !*** on T-fold, do not need to replace
                  !*** top row of physical domain, so jsrc should be greater than j

                  if (jsrc > j) then
                     ! do nothing
                  elseif (jsrc == j) then
                     ! don't average in the scatter even though halo update does
                     ! LARRAY_G(i,j) = 0.5_dbl_kind * (ARRAY_G(i,jsrc) + isign*ARRAY_G(isrc,jsrc))
                  else
                     ! copy
                     LARRAY_G(i,j) = isign * ARRAY_G(isrc,jsrc)
                  endif
               enddo
               enddo
            else
               !--- bottom edge
               do j = 1-nghost, 0
               do i = 1, nx_global
                  if (ns_boundary_type == 'cyclic') then
                     LARRAY_G(i,j) = ARRAY_G(i,j+ny_global)
                  elseif (ns_boundary_type == 'zero_gradient') then
                     LARRAY_G(i,j) = ARRAY_G(i,1)
                  elseif (ns_boundary_type == 'linear_extrap') then
                     efac = real(2-j,dbl_kind)
                     LARRAY_G(i,j) = efac*ARRAY_G(i,1) - (efac-c1)*ARRAY_G(i,2)
                  endif
               enddo
               enddo
               !--- top edge
               do j = ny_global+1, ny_global+nghost
               do i = 1, nx_global
                  if (ns_boundary_type == 'cyclic') then
                     LARRAY_G(i,j) = ARRAY_G(i,j-ny_global)
                  elseif (ns_boundary_type == 'zero_gradient') then
                     LARRAY_G(i,j) = ARRAY_G(i,ny_global)
                  elseif (ns_boundary_type == 'linear_extrap') then
                     efac = real(j-ny_global+1,dbl_kind)
                     LARRAY_G(i,j) = efac*ARRAY_G(i,ny_global) - (efac-c1)*ARRAY_G(i,ny_global-1)
                  endif
               enddo
               enddo
            endif

            do j = 1-nghost, ny_global+nghost
            !--- left edge
            do i = 1-nghost, 0
               if (ew_boundary_type == 'cyclic') then
                  LARRAY_G(i,j) = LARRAY_G(i+nx_global,j)
               elseif (ew_boundary_type == 'zero_gradient') then
                  LARRAY_G(i,j) = LARRAY_G(1,j)
               elseif (ew_boundary_type == 'linear_extrap') then
                  efac = real(2-i,dbl_kind)
                  LARRAY_G(i,j) = efac*LARRAY_G(1,j) - (efac-c1)*LARRAY_G(2,j)
               endif
            enddo
            !--- right edge
            do i = nx_global+1, nx_global+nghost
               if (ew_boundary_type == 'cyclic') then
                  LARRAY_G(i,j) = LARRAY_G(i-nx_global,j)
               elseif (ew_boundary_type == 'zero_gradient') then
                  LARRAY_G(i,j) = LARRAY_G(nx_global,j)
               elseif (ew_boundary_type == 'linear_extrap') then
                  efac = real(i-nx_global+1,dbl_kind)
                  LARRAY_G(i,j) = efac*LARRAY_G(nx_global,j) - (efac-c1)*LARRAY_G(nx_global-1,j)
               endif
            enddo
            enddo

         endif   ! noupdate
      endif   ! lext

      !*** send non-local blocks away

#ifndef NO_MPI
      allocate (msg_buffer(nx_block,ny_block))

      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) > 0 .and. &
             dst_dist%blockLocation(n)-1 /= my_task) then

            msg_buffer = lfillValue
            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi

            do j=jlo-nghost,jhi+nghost
            do i=ilo-nghost,ihi+nghost
               ! fill entire block
               isrc = this_block%i_glob(ilo) + i - ilo
               jsrc = this_block%j_glob(jlo) + j - jlo
               msg_buffer(i,j) = LARRAY_G(isrc,jsrc)
            enddo
            enddo

            call MPI_SEND(msg_buffer, nx_block*ny_block, &
                          mpiR4, dst_dist%blockLocation(n)-1, 3*mpitag_gs+n, &
                          MPI_COMM_ICE, ierr)

         endif
      end do

      deallocate(msg_buffer)
#endif
      !*** copy any local blocks

      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) == my_task+1) then
            dst_block = dst_dist%blockLocalID(n)
            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi

            do j=jlo-nghost,jhi+nghost
            do i=ilo-nghost,ihi+nghost
               ! fill entire block
               isrc = this_block%i_glob(ilo) + i - ilo
               jsrc = this_block%j_glob(jlo) + j - jlo
               ARRAY(i,j,dst_block) = LARRAY_G(isrc,jsrc)
            enddo
            enddo
         endif
      end do

#ifndef NO_MPI
!-----------------------------------------------------------------------
!
!  otherwise receive data from src_task
!
!-----------------------------------------------------------------------

   else   ! my_task /= src_task

      allocate (rcv_request(nblocks_tot), &
                rcv_status(MPI_STATUS_SIZE, nblocks_tot))

      rcv_request = 0
      rcv_status  = 0

      nrecvs = 0
      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) == my_task+1) then
            nrecvs = nrecvs + 1
            dst_block = dst_dist%blockLocalID(n)
            call MPI_IRECV(ARRAY(1,1,dst_block), nx_block*ny_block, &
                          mpiR4, src_task, 3*mpitag_gs+n, &
                          MPI_COMM_ICE, rcv_request(nrecvs), ierr)
         endif
      end do

      if (nrecvs > 0) &
         call MPI_WAITALL(nrecvs, rcv_request, rcv_status, ierr)

      deallocate(rcv_request, rcv_status)
#endif
   endif   ! my_task == src_task

#ifndef NO_MPI
   if (add_mpi_barriers) then
     call ice_barrier()
   endif
#endif

!-----------------------------------------------------------------------

 end subroutine scatter_globalR4

!***********************************************************************

 subroutine gather_globalI4(ARRAY_G, ARRAY, dst_task, src_dist, fillValue, grid_ext)

!  Generated by ./generate_GatherScatter.sh on 2026-08-09
!  This subroutine gathers a distributed array to a global-sized
!  array on the processor dst_task.
!  If grid_ext is true, then ARRAY_G is extended grid
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global

   integer (int_kind), intent(in) :: &
      dst_task   ! task to which array should be gathered

   type (distrb), intent(in) :: &
      src_dist   ! distribution of blocks in the source array

   integer (int_kind), dimension(:,:,:), intent(in) :: &
      ARRAY      ! array containing horizontal slab of distributed field

   integer (int_kind), intent(in), optional :: &
      fillValue  ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext   ! extended global grid flag

   integer (int_kind), dimension(:,:), intent(inout) :: &
      ARRAY_G    ! array containing global horizontal field on dst_task

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind) :: &
      i,j,n,          &! dummy loop counters
      iblock,jblock,  &! block index
      ilo,ihi,jlo,jhi  ! block sizes

#ifndef NO_MPI
   integer (int_kind) :: &
      nsends,         &! number of actual sends
      src_block,      &! block locator for send
      ierr             ! MPI error flag

   integer (int_kind), dimension(MPI_STATUS_SIZE) :: &
      status

   integer (int_kind), dimension(:), allocatable :: &
      snd_request

   integer (int_kind), dimension(:,:), allocatable :: &
      snd_status

   integer (int_kind), dimension(:,:), allocatable :: &
      msg_buffer
#endif

   integer (int_kind) :: &
      lfillValue  ! local special value

   logical (log_kind) :: &
      lext        ! local grid_ext global grid flag

   type (block) :: &
      this_block  ! block info for current block

   integer (int_kind), dimension(:,:), allocatable :: &
      LARRAY_G    ! array containing global horizontal field on dst_task
                  ! but with indexing that matches nx_global, ny_global
                  ! to simplify overlapping ext and non-ext coding.
                  ! for non-ext, ARRAY_G and LARRAY_G are (nx_global,ny_global).
                  ! for ext incoming ARRAY_G is (1:nx_global+2*nghost,1:ny_global+2*nghost)
                  ! LARRAY_G is same size, but indexing is
                  !            (1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
                  ! Could maybe use a pointer but a separate array and copy is more robust

   character(len=*), parameter :: subname = '(gather_globalI4)'

   if (present(fillValue)) then
      lfillValue = fillValue
   else
      lfillValue = spval_int
   endif

   if (present(grid_ext)) then
      lext = grid_ext
   else
      lext = .false.
   endif

!-----------------------------------------------------------------------
!
!  if this task is the dst_task, copy local blocks into the global
!  array and post receives for non-local blocks.
!
!-----------------------------------------------------------------------

   if (my_task == dst_task) then

      if (lext) then
         allocate(LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost))
         LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost) = ARRAY_G(1:nx_global+2,1:ny_global+2)
      else
         allocate(LARRAY_G(1:nx_global,1:ny_global))
         LARRAY_G(:,:) = ARRAY_G(:,:)
      endif

      do n=1,nblocks_tot

         this_block = get_block(n,n)
         ilo = this_block%ilo
         ihi = this_block%ihi
         jlo = this_block%jlo
         jhi = this_block%jhi
         iblock = this_block%iblock
         jblock = this_block%jblock

         !*** copy local blocks

         if (src_dist%blockLocation(n) == my_task+1) then

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = ARRAY(i,j,src_dist%blockLocalID(n))
            end do
            end do

            !*** fill outside halo for extended grid gather

            if (lext) then
               ! south
               if (jblock == 1) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),j-nghost) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! north
               if (jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),ny_global+j) = ARRAY(i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! west
               if (iblock == 1) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(i-nghost,this_block%j_glob(j)) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! east
               if (iblock == nblocks_x) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(nx_global+i,this_block%j_glob(j)) = ARRAY(ihi+i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! southwest
               if (iblock == 1 .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,j-nghost) = ARRAY(i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! northwest
               if (iblock == 1 .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,ny_global+j) = ARRAY(i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! southeast
               if (iblock == nblocks_x .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,j-nghost) = ARRAY(ihi+i,j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif

               ! northeast
               if (iblock == nblocks_x .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,ny_global+nghost) = ARRAY(ihi+i,jhi+j,src_dist%blockLocalID(n))
                  enddo
                  enddo
               endif
            endif

         !*** fill land blocks with special values

         else if (src_dist%blockLocation(n) == 0) then

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = lfillValue
            end do
            end do

         endif

      end do

#ifndef NO_MPI
      !*** copy blocks from other tasks

      allocate (msg_buffer(nx_block,ny_block))

      do n=1,nblocks_tot
         if (src_dist%blockLocation(n) > 0 .and. &
             src_dist%blockLocation(n) /= my_task+1) then

            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi
            iblock = this_block%iblock
            jblock = this_block%jblock

            call MPI_RECV(msg_buffer, size(msg_buffer), &
                 MPI_INTEGER, src_dist%blockLocation(n)-1, 3*mpitag_gs+n, &
                 MPI_COMM_ICE, status, ierr)

            do j = jlo, jhi
            do i = ilo, ihi
               LARRAY_G(this_block%i_glob(i),this_block%j_glob(j)) = msg_buffer(i,j)
            end do
            end do

            !*** fill outside halo for extended grid gather

            if (lext) then
               ! south
               if (jblock == 1) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),j-nghost) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! north
               if (jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = ilo, ihi
                     LARRAY_G(this_block%i_glob(i),ny_global+j) = msg_buffer(i,jhi+j)
                  enddo
                  enddo
               endif

               ! west
               if (iblock == 1) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(i-nghost,this_block%j_glob(j)) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! east
               if (iblock == nblocks_x) then
                  do j = jlo, jhi
                  do i = 1, nghost
                     LARRAY_G(nx_global+i,this_block%j_glob(j)) = msg_buffer(ihi+i,j)
                  enddo
                  enddo
               endif

               ! southwest
               if (iblock == 1 .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,j-nghost) = msg_buffer(i,j)
                  enddo
                  enddo
               endif

               ! northwest
               if (iblock == 1 .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(i-nghost,ny_global+j) = msg_buffer(i,jhi+j)
                  enddo
                  enddo
               endif

               ! southeast
               if (iblock == nblocks_x .and. jblock == 1) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,j-nghost) = msg_buffer(ihi+i,j)
                  enddo
                  enddo
               endif

               ! northeast
               if (iblock == nblocks_x .and. jblock == nblocks_y) then
                  do j = 1, nghost
                  do i = 1, nghost
                     LARRAY_G(nx_global+nghost,ny_global+nghost) = msg_buffer(ihi+i,jhi+j)
                  enddo
                  enddo
               endif
            endif ! lext
         endif
      end do

      deallocate(msg_buffer)
#endif

      ! copy LARRAY_G to ARRAY_G, offset extended grid index

      if (lext) then
         ARRAY_G(1:nx_global+2,1:ny_global+2) = LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
      else
         ARRAY_G(1:nx_global,1:ny_global) = LARRAY_G(1:nx_global,1:ny_global)
      endif
      deallocate(LARRAY_G)

#ifndef NO_MPI
!-----------------------------------------------------------------------
!
!  otherwise send data to dst_task
!
!-----------------------------------------------------------------------

   else

      allocate(snd_request(nblocks_tot), &
               snd_status (MPI_STATUS_SIZE, nblocks_tot))

      nsends = 0
      do n=1,nblocks_tot
         if (src_dist%blockLocation(n) == my_task+1) then
            nsends = nsends + 1
            src_block = src_dist%blockLocalID(n)
            call MPI_ISEND(ARRAY(1,1,src_block), nx_block*ny_block, &
                 MPI_INTEGER, dst_task, 3*mpitag_gs+n, &
                 MPI_COMM_ICE, snd_request(nsends), ierr)
         endif
      end do

      if (nsends > 0) call MPI_WAITALL(nsends, snd_request, snd_status, ierr)
      deallocate(snd_request, snd_status)
#endif

   endif

#ifndef NO_MPI
   if (add_mpi_barriers) then
      call ice_barrier()
   endif
#endif

!-----------------------------------------------------------------------

 end subroutine gather_globalI4

!***********************************************************************

 subroutine scatter_globalI4(ARRAY, ARRAY_G, src_task, dst_dist, &
                             field_loc, field_type, fillValue, &
                             grid_ext)

!  Generated by ./generate_GatherScatter.sh on 2026-08-09
!  This subroutine scatters a global sized array from src_task to all
!  processors.
!  If grid_ext is true, then ARRAY_G is extended grid and updates outer halo
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global and outer
!    halo is updated for cyclic and tripole bcs.
!  If grid_ext is false and interior is true, then only the interior data will 
!    be scattered, no outer halo bcs will be applied

   integer (int_kind), intent(in) :: &
      src_task        ! task from which array should be scattered

   type (distrb), intent(in) :: &
      dst_dist        ! distribution of resulting blocks

   integer (int_kind), dimension(:,:), intent(in) :: &
      ARRAY_G         ! array containing global field on src_task

   integer (int_kind), intent(in), optional :: &
      field_type,    &! id for type of field (scalar, vector, angle)
      field_loc       ! id for location on horizontal grid
                      !  (center, NEcorner, Nface, Eface)

   integer (int_kind), intent(in), optional :: &
      fillValue       ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext        ! extended grid flag

   integer (int_kind), dimension(:,:,:), intent(inout) :: &
      ARRAY           ! array containing distributed field

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind) :: &
      i,j,n,         &! dummy loop indices
      ilo,ihi,jlo,jhi,&! block indices
      isrc, jsrc,    &! source addresses
      ioffset, joffset,   &! offsets for tripole boundary conditions
      isign,         &! sign factor for tripole boundary conditions
      dst_block       ! location of block in dst array

   real (dbl_kind) :: &
      efac            ! linear extrapolation factor

   type (block) :: &
      this_block      ! block info for current block

   integer (int_kind) :: &
      lfillValue      ! local special value

   logical (log_kind) :: &
      lext,          &! local extended global grid flag
      noupdate        ! flag if noupdate is on

   integer (int_kind), dimension(:,:), allocatable :: &
      LARRAY_G    ! array containing global horizontal field on dst_task
                  ! but with indexing that matches nx_global, ny_global
                  ! to simplify overlapping ext and non-ext coding.
                  ! for non-ext, ARRAY_G and LARRAY_G are (nx_global,ny_global).
                  ! for ext incoming ARRAY_G is (1:nx_global+2*nghost,1:ny_global+2*nghost)
                  ! LARRAY_G is same size, but indexing is
                  !            (1-nghost:nx_global+nghost,1-nghost:ny_global+nghost)
                  ! Could maybe use a pointer but a separate array and copy is more robust

#ifndef NO_MPI
   integer (int_kind) :: &
      nrecvs,        &! actual number of messages received
      ierr            ! MPI error flag

   integer (int_kind), dimension(:), allocatable :: &
      rcv_request     ! request array for receives

   integer (int_kind), dimension(:,:), allocatable :: &
      rcv_status      ! status array for receives

   integer (int_kind), dimension(:,:), allocatable :: &
      msg_buffer      ! buffer for sending blocks
#endif

   character(len=*), parameter :: subname = '(scatter_globalI4)'

   if (present(fillValue)) then
      lfillValue = fillValue
   else
      lfillValue = 0
   endif

   if (present(grid_ext)) then
      lext = grid_ext
   else
      lext = .false.
   endif

   noupdate = .false.
   if (present(field_loc)) then
      if (field_loc == field_loc_noupdate) then
         noupdate = .true.
      endif
   endif
   if (present(field_type)) then
      if (field_type == field_type_noupdate) then
         noupdate = .true.
      endif
   endif

   ! check size of global grid
   if (my_task == src_task) then
      if (lext) then
         if (size(ARRAY_G,dim=1)/= nx_global+2*nghost .or. size(ARRAY_G,dim=2) /= ny_global+2*nghost) then
            call abort_ice(subname//'ERROR: grid_ext = true, wrong ARRAY_G size')
         endif
      else
         if (size(ARRAY_G,dim=1)/= nx_global .or. size(ARRAY_G,dim=2) /= ny_global) then
            call abort_ice(subname//'ERROR: grid_ext = false, wrong ARRAY_G size')
         endif
      endif
   endif

   ARRAY = lfillValue

   isign = -99
   ioffset = -999
   joffset = -999
   if (.not.lext .and. .not.noupdate .and. &
      (ns_boundary_type == 'tripole' .or. ns_boundary_type == 'tripoleT')) then

      select case (field_type)
      case (field_type_scalar)
         isign =  1
      case (field_type_vector)
         isign = -1
      case (field_type_angle)
         isign = -1
      case (field_type_noupdate) ! ghost cells never used - use cell center
         isign =  1
      case default
         call abort_ice(subname//'ERROR: Unknown field kind')
      end select

      if (ns_boundary_type == 'tripole') then
         ioffset = 0
         joffset = 0
      else ! tripoleT fold
         ioffset = -1
         joffset = 1
      endif

      select case (field_loc)
        case (field_loc_center)     ! cell center location
           !ioffset = ioffset
           !joffset = joffset
        case (field_loc_NEcorner)   ! cell corner (velocity) location
           ioffset = ioffset + 1
           joffset = joffset + 1
        case (field_loc_Eface)      ! cell east face
           ioffset = ioffset + 1
           !joffset = joffset
        case (field_loc_Nface)      ! cell north face
           !ioffset = ioffset
           joffset = joffset + 1
        case (field_loc_noupdate)   ! no update
           !ioffset = ioffset
           !joffset = joffset
        case default
           call abort_ice(subname//'ERROR: Unknown field location')
      end select

   endif ! not lext

!-----------------------------------------------------------------------
!
!  if this task is the src_task, compute updated LARRAY_G which contains
!  outer halo extended grid from ARRAY_G (extended or not), fill outer
!  halo in global array then scatter
!
!  i_global, j_global are indexed 1-nghost:n*_global+nghost
!
!-----------------------------------------------------------------------

   if (my_task == src_task) then

      allocate(LARRAY_G(1-nghost:nx_global+nghost,1-nghost:ny_global+nghost))

      LARRAY_G = lfillValue
      if (lext) then
         do j = 1-nghost, ny_global+nghost
         do i = 1-nghost, nx_global+nghost
            LARRAY_G(i,j) = ARRAY_G(i+nghost,j+nghost)
         enddo
         enddo
      else

         ! fill cells that can be directly copied

         do j = 1-nghost, ny_global+nghost
         do i = 1-nghost, nx_global+nghost
            isrc = i_global(i)
            jsrc = j_global(j)
            if (isrc >= 1 .and. isrc <= nx_global .and. &
                jsrc >= 1 .and. jsrc <= ny_global) then
               ! copy valid cell directly
               LARRAY_G(i,j) = ARRAY_G(isrc,jsrc)
            endif
         enddo
         enddo

         ! fill outer halo, only if noupdate is false
         ! do north/south boundary first (partly due to tripole feature) (1:nx_global)
         ! then do east/west including corners (1-nghost:ny_global+nghost)

         if (.not.noupdate) then
            if (ns_boundary_type == 'tripole' .or. ns_boundary_type == 'tripoleT') then
               do j = ny_global, ny_global+nghost
               ! north of active cells
               do i = 1, nx_global
                  isrc = nx_global - i + 1 - ioffset   ! ioffset = 0 for u center, ioffset = 1 for T center
                  jsrc = ny_global - (j-ny_global) - joffset + 1  ! joffset = 0 for u center, joffset = 1 for T center
                  if (isrc < 1        ) isrc = isrc + nx_global
                  if (isrc > nx_global) isrc = isrc - nx_global

                  !*** for center and Eface on u-fold, and NE corner and Nface
                  !*** on T-fold, do not need to replace
                  !*** top row of physical domain, so jsrc should be greater than j

                  if (jsrc > j) then
                     ! do nothing
                  elseif (jsrc == j) then
                     ! don't average in the scatter even though halo update does
                     ! LARRAY_G(i,j) = 0.5_dbl_kind * (ARRAY_G(i,jsrc) + isign*ARRAY_G(isrc,jsrc))
                  else
                     ! copy
                     LARRAY_G(i,j) = isign * ARRAY_G(isrc,jsrc)
                  endif
               enddo
               enddo
            else
               !--- bottom edge
               do j = 1-nghost, 0
               do i = 1, nx_global
                  if (ns_boundary_type == 'cyclic') then
                     LARRAY_G(i,j) = ARRAY_G(i,j+ny_global)
                  elseif (ns_boundary_type == 'zero_gradient') then
                     LARRAY_G(i,j) = ARRAY_G(i,1)
                  elseif (ns_boundary_type == 'linear_extrap') then
                     efac = real(2-j,dbl_kind)
                     LARRAY_G(i,j) = efac*ARRAY_G(i,1) - (efac-c1)*ARRAY_G(i,2)
                  endif
               enddo
               enddo
               !--- top edge
               do j = ny_global+1, ny_global+nghost
               do i = 1, nx_global
                  if (ns_boundary_type == 'cyclic') then
                     LARRAY_G(i,j) = ARRAY_G(i,j-ny_global)
                  elseif (ns_boundary_type == 'zero_gradient') then
                     LARRAY_G(i,j) = ARRAY_G(i,ny_global)
                  elseif (ns_boundary_type == 'linear_extrap') then
                     efac = real(j-ny_global+1,dbl_kind)
                     LARRAY_G(i,j) = efac*ARRAY_G(i,ny_global) - (efac-c1)*ARRAY_G(i,ny_global-1)
                  endif
               enddo
               enddo
            endif

            do j = 1-nghost, ny_global+nghost
            !--- left edge
            do i = 1-nghost, 0
               if (ew_boundary_type == 'cyclic') then
                  LARRAY_G(i,j) = LARRAY_G(i+nx_global,j)
               elseif (ew_boundary_type == 'zero_gradient') then
                  LARRAY_G(i,j) = LARRAY_G(1,j)
               elseif (ew_boundary_type == 'linear_extrap') then
                  efac = real(2-i,dbl_kind)
                  LARRAY_G(i,j) = efac*LARRAY_G(1,j) - (efac-c1)*LARRAY_G(2,j)
               endif
            enddo
            !--- right edge
            do i = nx_global+1, nx_global+nghost
               if (ew_boundary_type == 'cyclic') then
                  LARRAY_G(i,j) = LARRAY_G(i-nx_global,j)
               elseif (ew_boundary_type == 'zero_gradient') then
                  LARRAY_G(i,j) = LARRAY_G(nx_global,j)
               elseif (ew_boundary_type == 'linear_extrap') then
                  efac = real(i-nx_global+1,dbl_kind)
                  LARRAY_G(i,j) = efac*LARRAY_G(nx_global,j) - (efac-c1)*LARRAY_G(nx_global-1,j)
               endif
            enddo
            enddo

         endif   ! noupdate
      endif   ! lext

      !*** send non-local blocks away

#ifndef NO_MPI
      allocate (msg_buffer(nx_block,ny_block))

      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) > 0 .and. &
             dst_dist%blockLocation(n)-1 /= my_task) then

            msg_buffer = lfillValue
            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi

            do j=jlo-nghost,jhi+nghost
            do i=ilo-nghost,ihi+nghost
               ! fill entire block
               isrc = this_block%i_glob(ilo) + i - ilo
               jsrc = this_block%j_glob(jlo) + j - jlo
               msg_buffer(i,j) = LARRAY_G(isrc,jsrc)
            enddo
            enddo

            call MPI_SEND(msg_buffer, nx_block*ny_block, &
                          MPI_INTEGER, dst_dist%blockLocation(n)-1, 3*mpitag_gs+n, &
                          MPI_COMM_ICE, ierr)

         endif
      end do

      deallocate(msg_buffer)
#endif
      !*** copy any local blocks

      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) == my_task+1) then
            dst_block = dst_dist%blockLocalID(n)
            this_block = get_block(n,n)
            ilo = this_block%ilo
            ihi = this_block%ihi
            jlo = this_block%jlo
            jhi = this_block%jhi

            do j=jlo-nghost,jhi+nghost
            do i=ilo-nghost,ihi+nghost
               ! fill entire block
               isrc = this_block%i_glob(ilo) + i - ilo
               jsrc = this_block%j_glob(jlo) + j - jlo
               ARRAY(i,j,dst_block) = LARRAY_G(isrc,jsrc)
            enddo
            enddo
         endif
      end do

#ifndef NO_MPI
!-----------------------------------------------------------------------
!
!  otherwise receive data from src_task
!
!-----------------------------------------------------------------------

   else   ! my_task /= src_task

      allocate (rcv_request(nblocks_tot), &
                rcv_status(MPI_STATUS_SIZE, nblocks_tot))

      rcv_request = 0
      rcv_status  = 0

      nrecvs = 0
      do n=1,nblocks_tot
         if (dst_dist%blockLocation(n) == my_task+1) then
            nrecvs = nrecvs + 1
            dst_block = dst_dist%blockLocalID(n)
            call MPI_IRECV(ARRAY(1,1,dst_block), nx_block*ny_block, &
                          MPI_INTEGER, src_task, 3*mpitag_gs+n, &
                          MPI_COMM_ICE, rcv_request(nrecvs), ierr)
         endif
      end do

      if (nrecvs > 0) &
         call MPI_WAITALL(nrecvs, rcv_request, rcv_status, ierr)

      deallocate(rcv_request, rcv_status)
#endif
   endif   ! my_task == src_task

#ifndef NO_MPI
   if (add_mpi_barriers) then
     call ice_barrier()
   endif
#endif

!-----------------------------------------------------------------------

 end subroutine scatter_globalI4

!***********************************************************************
! autogenerate end
!***********************************************************************

 subroutine gather_globalL1(ARRAY_G, ARRAY, dst_task, src_dist, fillValue, grid_ext)

!  Convert to integer and call gather_globalI4
!  This subroutine gathers a distributed array to a global-sized
!  array on the processor dst_task.
!  If grid_ext is true, then ARRAY_G is extended grid
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global

   integer (int_kind), intent(in) :: &
      dst_task   ! task to which array should be gathered

   type (distrb), intent(in) :: &
      src_dist   ! distribution of blocks in the source array

   logical (log_kind), dimension(:,:,:), intent(in) :: &
      ARRAY      ! array containing horizontal slab of distributed field

   logical (log_kind), intent(in), optional :: &
      fillValue  ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext   ! extended global grid flag

   logical (log_kind), dimension(:,:), intent(inout) :: &
      ARRAY_G    ! array containing global horizontal field on dst_task

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind), dimension(:,:,:), allocatable :: &
      IARRAY     ! integer array containing horizontal slab of distributed field

   integer (int_kind), dimension(:,:), allocatable :: &
      IARRAY_G   ! integer array containing global horizontal field on dst_task

   integer (int_kind) :: &
      ifillValue ! integer fill value

   character(len=*), parameter :: subname = '(gather_globalL1)'

   allocate(IARRAY(size(ARRAY,dim=1),size(ARRAY,dim=2),size(ARRAY,dim=3)))
   allocate(IARRAY_G(size(ARRAY_G,dim=1),size(ARRAY_G,dim=2)))

   IARRAY = 0   ! 0 = false
   where (ARRAY) IARRAY = 1   ! 1 = true
   IARRAY_G = 0
   where (ARRAY_G) IARRAY_G = 1

   if (present(fillValue)) then
      ifillValue = 0
      if (fillValue) ifillValue = 1
      call gather_global(IARRAY_G, IARRAY, dst_task, src_dist, ifillValue, grid_ext)
   else
      call gather_global(IARRAY_G, IARRAY, dst_task, src_dist, grid_ext = grid_ext)
   endif

   ARRAY_G = .false.  ! 0 = false
   where (mod(abs(IARRAY_G),2) == 1) ARRAY_G = .true.  ! .ne.0 = true

!-----------------------------------------------------------------------

 end subroutine gather_globalL1

!***********************************************************************

 subroutine scatter_globalL1(ARRAY, ARRAY_G, src_task, dst_dist, &
                               field_loc, field_type, fillValue, &
                               grid_ext)

!  Convert to integer and call scatter_globalI4
!  This subroutine scatters a global sized array from src_task to all
!  processors.
!  If grid_ext is true, then ARRAY_G is extended grid and updates outer halo
!  If grid_ext is false, then ARRAY_G is 1:nx_global,1:ny_global and outer
!    halo is updated for cyclic and tripole bcs.
!  If grid_ext is false and interior is true, then only the interior data will
!    be scattered, no outer halo bcs will be applied

   integer (int_kind), intent(in) :: &
      src_task        ! task from which array should be scattered

   type (distrb), intent(in) :: &
      dst_dist        ! distribution of resulting blocks

   logical (log_kind), dimension(:,:), intent(in) :: &
      ARRAY_G         ! array containing global field on src_task

   integer (int_kind), intent(in), optional :: &
      field_type,    &! id for type of field (scalar, vector, angle)
      field_loc       ! id for location on horizontal grid
                      !  (center, NEcorner, Nface, Eface)

   logical (log_kind), intent(in), optional :: &
      fillValue       ! special value

   logical (log_kind), intent(in), optional :: &
      grid_ext        ! extended grid flag

   logical (log_kind), dimension(:,:,:), intent(inout) :: &
      ARRAY           ! array containing distributed field

!-----------------------------------------------------------------------
!
!  local variables
!
!-----------------------------------------------------------------------

   integer (int_kind), dimension(:,:,:), allocatable :: &
      IARRAY     ! integer array containing horizontal slab of distributed field

   integer (int_kind), dimension(:,:), allocatable :: &
      IARRAY_G   ! integer array containing global horizontal field on dst_task

   integer (int_kind) :: &
      ifillValue ! integer fill value

   character(len=*), parameter :: subname = '(scatter_globalL1)'

   allocate(IARRAY(size(ARRAY,dim=1),size(ARRAY,dim=2),size(ARRAY,dim=3)))
   allocate(IARRAY_G(size(ARRAY_G,dim=1),size(ARRAY_G,dim=2)))

   IARRAY_G = 0   ! 0 = false
   where (ARRAY_G) IARRAY_G = 1   ! 1 = true

   if (present(fillValue)) then
      ifillValue = 0
      if (fillValue) ifillValue = 1
      call scatter_global(IARRAY, IARRAY_G, src_task, dst_dist, &
                          field_loc, field_type, ifillValue, grid_ext)
   else
      call scatter_global(IARRAY, IARRAY_G, src_task, dst_dist, &
                          field_loc, field_type, grid_ext=grid_ext)
   endif

   ARRAY = .false.  ! 0 = false
   where (mod(abs(IARRAY),2) == 1) ARRAY = .true.  ! .ne.0 = true

!-----------------------------------------------------------------------

 end subroutine scatter_globalL1

!***********************************************************************

 end module ice_gather_scatter

!|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
